name: Unix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure and build without format dependencies
      run: |
        cmake -Htest -Bbuild -DFORMAT_CHECK_CMAKE=True
        cmake --build build
        ./build/test

    - name: Install format dependencies
      run: |
        brew install clang-format
        pip install cmake_format

    - name: Configure
      run: cmake -Htest -Bbuild -DFORMAT_CHECK_CMAKE=True

    - name: Run format
      run: "cmake --build build --target format"

    - name: Check clang-format
      run: "! cmake --build build --target check-clang-format"

    - name: Check cmake-format
      run: "! cmake --build build --target check-cmake-format"

    - name: Check format
      run: "! cmake --build build --target check-format"

    - name: Fix format
      run: cmake --build build --target fix-format

    - name: Check fixed format
      run: cmake --build build --target check-format && ! git diff --exit-code
