name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure and build without format dependencies
      shell: bash
      run: |
        cmake -Htest -Bbuild -DFORMAT_CHECK_CMAKE=True
        cmake --build build
        ./build/test.exe

    - name: Install clang-format
      run: |
        choco install llvm -y
        echo "::add-path::C:\\Program Files\\LLVM\\bin"

    - name: Install cmake-format
      run: pip install cmake_format

    - name: Configure
      shell: bash
      run: cmake -Htest -Bbuild -DFORMAT_CHECK_CMAKE=True

    - name: Run format
      shell: bash
      run: "cmake --build build --target format"

    - name: Check clang-format
      shell: bash
      run: "! cmake --build build --target check-clang-format"

    - name: Check cmake-format
      shell: bash
      run: "! cmake --build build --target check-cmake-format"

    - name: Check format
      shell: bash
      run: "! cmake --build build --target check-format"

    - name: Fix format
      shell: bash
      run: cmake --build build --target fix-format

    - name: Check fixed format
      shell: bash
      run: cmake --build build --target check-format && ! git diff --exit-code
